name: Run Python Code with OpenAI API Key

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create a dummy Python script
        run: |
          echo 'import os
          openai_api_key = os.getenv("OPENAI_API_KEY")

          if openai_api_key is None:
              print("Error: OPENAI_API_KEY is not set.")
          else:
              print("Successfully retrieved OPENAI_API_KEY.")
              # Optionally, check if the key starts with the correct prefix for OpenAI keys
              if openai_api_key.startswith("sk-"):
                  print("The API key looks valid.")
              else:
                  print("Warning: The API key does not look valid.")' > app.py

      - name: Run the app.py script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Pull secret from GitHub secrets
        run: |
          python app.py
