name: Run Python Code with OpenAI API Key

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create a dummy Python script
        run: |
          echo "import os
          openai_api_key = os.getenv('OPENAI_API_KEY')
          print('Using OpenAI API Key:', openai_api_key)" > app.py

      - name: Run the app.py script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Pull secret from GitHub secrets
        run: |
          python app.py
